name: "Build and deploy Release"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Git tag (X.Y.Z)
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ inputs.tag }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO: ${{ github.event.repository.full_name }}

jobs:
  check-input:
    runs-on: [ self-hosted, linux, weu ]
    steps:
      - name: Validate inputs
        shell: bash
        run: |
          if ! [[ ${GITHUB_REF} =~ ^refs/heads/release/[0-9]+\.[0-9]+$ ]]; then
            echo 'You can only create a release from a "release/${major}.${minor}" branch'
            exit 1
          fi

          if ! [[ ${{ inputs.tag }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo 'The tag needs to be in the form X.Y.Z'
            exit 1
          fi

          if ! [[ $(echo ${{ inputs.tag }} | grep -o '^[0-9]\+\.[0-9]\+') == $(echo ${GITHUB_REF} | cut -c 29-) ]]; then
            echo 'The tag major and minor versions need to match the branch name'
            exit 1
          fi

  release:
    runs-on: [self-hosted, linux, we]
    needs: [ check-input ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build
      - name: Resolve https://github.com/actions/checkout/issues/11
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.email ${{ github.event.pusher.email }}
          git config --global user.name ${{ github.event.pusher.name }}
      - name: Release
        env:
          NEXUS_KL_HOST: ${{ secrets.NEXUS }}
          NEXUS_KL_USERNAME: ${{ secrets.NEXUS_KL_US }}
          NEXUS_KL_PASSWORD: ${{ secrets.NEXUS_KL_PA }}
        run: sbt 'release with-default release-version ${{ inputs.tag }}'

  copy-jar-to-hdfs:
    runs-on: [self-hosted, linux, we]
    needs: [ release ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Publish
        uses: ./.github/actions/copy-jar-to-hdfs
        with:
          tag: ${{ inputs.tag }}
          nexus-host: ${{ secrets.NEXUS_KL_HOST }}
          ansible-tower-token: ${{ secrets.ANSIBLE_TOWER_TOK }}
          job_template_id: ${{ vars.ANSIBLE_TOWER_JOB_TEMPLATE_IDdd }}
